import React, { useEffect, useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import UploadButton from "../components/UploadButton";
import { AiOutlineDownload } from "react-icons/ai";
import { solveProblem } from "../endpoints/solver";
import { moneyFormatter } from "../components/utils";

export default function Home() {
  const [solveProblemSuccess, setSolveProblemSuccess] = useState(false);
  const [result, setResult] = useState(null);

  const problemName = "teste";

  const fetchSolverEndpoint = async (file) => {
    try {
      const response = await solveProblem({ file, problemName });
      setSolveProblemSuccess(true);
      setResult(response.data.result);
    } catch (err) {
      setSolveProblemSuccess(false);
    }
  };

  const onFileChange = (event) => {
    const file = event.target.files[0];

    fetchSolverEndpoint(file);
  };

  const renderResultsTable = () => (
    <div className={styles.table__container}>
      <table>
        <thead>
          <tr>
            <td> Material </td>
            <td> Unidade </td>
            <td> Valor </td>
          </tr>
        </thead>
        <tbody>
          {result &&
            Object.keys(result.vars).map((key) => (
              <tr key={key}>
                <td>{key}</td>
                <td> - </td>
                <td>{result?.vars[key].toFixed(2)}</td>
              </tr>
            ))}
        </tbody>
      </table>
    </div>
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.contentContainer}>
        <h1> Adicione a planilha com os dados </h1>
        <div>
          <div>
            <UploadButton onChange={onFileChange} />
          </div>
        </div>
        <a className={styles.downloadButton} href="dadosTeste.ods" download>
          Baixar modelo da planilha
          <AiOutlineDownload />
        </a>
        {solveProblemSuccess && renderResultsTable()}
      </div>
    </div>
  );
}
