import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <input type="file" />
      <h1> Resultados </h1>
      <p> F. objetivo : 3x1 + 2x2 + 5x2 = 20 </p>

      <a> Baixar excel </a>
    </div>
  );
}
